/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/insightsEngine`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/snapshot` | `/snapshot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/chat` | `/more/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/documents` | `/more/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/goals` | `/more/goals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/pricing` | `/more/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/profile` | `/more/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../lib/insightsEngine`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/snapshot` | `/snapshot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/chat` | `/more/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/documents` | `/more/documents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/goals` | `/more/goals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/pricing` | `/more/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more/profile` | `/more/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../lib/insightsEngine${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/snapshot${`?${string}` | `#${string}` | ''}` | `/snapshot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tracker${`?${string}` | `#${string}` | ''}` | `/tracker${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/chat${`?${string}` | `#${string}` | ''}` | `/more/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/documents${`?${string}` | `#${string}` | ''}` | `/more/documents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/goals${`?${string}` | `#${string}` | ''}` | `/more/goals${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/pricing${`?${string}` | `#${string}` | ''}` | `/more/pricing${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more/profile${`?${string}` | `#${string}` | ''}` | `/more/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/insightsEngine`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/snapshot` | `/snapshot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/chat` | `/more/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/documents` | `/more/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/goals` | `/more/goals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/pricing` | `/more/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more/profile` | `/more/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
